### ISSUE TITLE
build.sh Deb Pack Gen debarch if statement backwards

### ISSUE THREAD

**Issue by jxcang** [frank-w/BPI-R2-4.14#106]
https://github.com/frank-w/BPI-Router-Linux/blob/4aeab81edd3e64993364d76f9d9c2c3fd49e5fca/build.sh#L611
Line 611, c.f.
I believe only R64 is armhf. All others are arm64. The logic is backwards right now. If R64, debarch=arm64, no...

**Comment by frank-w** [comment]
hi,
this is the old (own-coded) deb function, i have not updated it after switching to kernels deb-script

ci uses kernels deb-creation function...but you are partly right...r2 is the only armhf and all others (r2pro,r64 and r3) are arm64

this own function is only available via build.sh choice or direct command, so i will change it

edit: have pushed change on 6.4-rc branch, will update the others too, but have not tested the function after adding r2pro and r3 with 6.1

**Comment by frank-w** [comment]
in 6.1 and 6.6 this is fixed, <=5.15 is only r2 and r64
