### ISSUE TITLE
[BPI-R4] File missing: ./arch/arm64/boot/dts/mediatek/mt7988a-bananapi-bpi-r4-sd.dtso  etc.

### ISSUE THREAD

**Issue by jcdutton** [frank-w/BPI-R2-4.14#120]
Hi,

The bpi-r4.its file in 6.9-rc  refers to "./arch/arm64/boot/dts/mediatek/mt7988a-bananapi-bpi-r4-sd.dtbo", so do you also have the "./arch/arm64/boot/dts/mediatek/mt7988a-bananapi-bpi-r4-sd.dtso" and all the other bpi-r4  dtso files?
Maybe you missed them off the repo.

**Comment by frank-w** [comment]
as i already told you in other issue, i have not yet added r4 related patches and so dts and some more is missing

**Comment by frank-w** [comment]
have now added (hopefully) all whats needed for r4 atm
