### ISSUE TITLE
[BPI-R4] Docker support

### ISSUE THREAD

**Issue by arosenhagen** [frank-w/BPI-R2-4.14#124]
Is there a way to get Docker working on a BPI-R4 with current Debian Bookworm Image? I tried different kernel versions but all stuck on the following error, when trying to start a docker-container:

`docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: bpf_prog_query(BPF_CGROUP_DEVICE) failed: invalid argument: unknown.`

Adding `systemd.unified_cgroup_hierarchy=0` to kernel parameters didn't help either.

**Comment by frank-w** [comment]
you need CONFIG_CGROUP_BPF selected in kernel, seems my r4 branches do not have it yet...

**Comment by arosenhagen** [comment]
if you give me a bit of a direction of where to actually add it I may build it on my own and test it ;-)

**Comment by frank-w** [comment]
pushed to 6.9-main/6.10-main branches so you can wait for pipeline to be complete or compile yourself (instructions in readme.md on default branch)

**Comment by frank-w** [comment]
Docker works now?

**Comment by arosenhagen** [comment]
yes - like a charm. thanks for the fast adjustment!
