### ISSUE TITLE
IFB module?

### ISSUE THREAD

**Issue by danielschonfeld** [frank-w/BPI-R2-4.14#126]
Is it posssible to add the IFB module to bookwarm for the bpi-r4? It seems like it would be useful for anybody who wants to give SQM a try

**Comment by frank-w** [comment]
Which module do you mean? I know only ifb for nftables which should be activated

**Comment by danielschonfeld** [comment]
This one
https://github.com/frank-w/BPI-Router-Linux/blob/89214dc3d3de95927217cd0102451a591949a8f7/drivers/net/Kconfig#L150

**Comment by frank-w** [comment]
Added in latest 6.10 release

https://github.com/frank-w/BPI-Router-Linux/releases/tag/CI-BUILD-6.10-main-6.10.0-2024-08-30_1239

**Comment by danielschonfeld** [comment]
That's fantastic, thank you! 
Question: if I currently run bookwarm with 6.9, do I just dump the contents of RPI-BOOT into the /boot partition while its running and the contents of RPI-ROOT into the appropriate / directories and reboot the system? it will load alright without any more change?
