### ISSUE TITLE
Add CAKE scheduler to tc

### ISSUE THREAD

**Issue by danielschonfeld** [frank-w/BPI-R2-4.14#129]
Same idea as adding IFB, CAKE is more modern and useful for SQM configurations.

Please consider adding this
https://github.com/frank-w/BPI-Router-Linux/blob/89214dc3d3de95927217cd0102451a591949a8f7/net/sched/Kconfig#L281

**Comment by frank-w** [comment]
Can you check if more options make sense for tc / queuing so i do not add options one-by-one

**Comment by danielschonfeld** [comment]
I’m not an expert on this but mostly I think this project (
https://github.com/tohojo/sqm-scripts) is the de facto “standard”. I think
once we add cake that should be it but I’m not promising anything.

Apologies for the piece meal requests!

**Comment by danielschonfeld** [comment]
Thank you for adding that scheduler.  I just tested it and that's all one needs for sqm-scripts so I believe we can close this issue.

👍
