### ISSUE TITLE
Update to cryptodev 1.10

### ISSUE THREAD

**Issue by Josue-T** [frank-w/BPI-R2-4.14#63]
Hello,

I also discovered that cryptodev bring some instability when I use sftp (so I disabled it to fix this issue).

Cryptodev 1.10 is released so, maybe upgrading to cryptodev 1.10 might fix the issue.

**Comment by frank-w** [comment]
Can you please try it before i do in my repo?

Sorry for late reply

**Comment by frank-w** [comment]
Cryptodev was updated in older trees (newer have no cryptodev yet)
