### ISSUE TITLE
F2FS on BananaPi

### ISSUE THREAD

**Issue by ghost** [frank-w/BPI-R2-4.14#66]
Is it possible to use f2fs FS on BananaPi? 
If yes, can you tell me how i can use it? 
Thanks a lot!

**Comment by frank-w** [comment]
F2fs is included as module

https://github.com/frank-w/BPI-R2-4.14/blob/9b9d2270c14ed5afd8066352c100f12cb2dd9a8d/arch/arm/configs/mt7623n_evb_fwu_defconfig#L486

So you can load module and should use it like other fs...if you want to use as rootf you need to change this to y and of courae change rootfstype in uenv.txt

**Comment by ghost** [comment]
Thanks a lot!
