### ISSUE TITLE
Problem 5.4.21-bpi-r2-main

### ISSUE THREAD

**Issue by ghost** [frank-w/BPI-R2-4.14#69]
Here I am again bothering you, but I need to install the header.
After moving to the penultimate kernel build installed with sudo dpkg -i x.deb i have rebooted and the bananapi r2 changed ip, no problem.

![immagine](https://user-images.githubusercontent.com/43168947/75146050-85832a80-56fa-11ea-9155-e6b79d483424.png)

I logged in and proceeded to install in the same way linux-libc-dev_5.4.21-bpi-r2-main-1_armhf.deb, no problem.

![immagine](https://user-images.githubusercontent.com/43168947/75146509-92544e00-56fb-11ea-990c-90b775e8bbde.png)

I had previously installed it, but I wanted to provide a screen that it works.

I reboot again and after the wget for obtein the image and the header i try to install it in the same way, but i obtein this errors..
![immagine](https://user-images.githubusercontent.com/43168947/75146097-a0559f00-56fa-11ea-9382-485147b7db2d.png)

![immagine](https://user-images.githubusercontent.com/43168947/75146169-cda24d00-56fa-11ea-8364-a5cc6f2c2fb3.png)

How can I solve it? Many thanks in advance

**Comment by frank-w** [comment]
you have already installed this kernel-version...you need to uninstall first to install again

**Comment by ghost** [comment]
Perfect, I managed to fix the 5.4.21 kernel.
I put the header, the image and the libc in the bananapi.
Now the problem is here ..

![immagine](https://user-images.githubusercontent.com/43168947/75235476-98f6ca00-57bc-11ea-9bc5-d5f8cd48ce7b.png)

During the wireguard installation the necessary modules are compiled with dkms for older kernels, they complete without any problem, but..

![immagine](https://user-images.githubusercontent.com/43168947/75235615-cfcce000-57bc-11ea-81ef-6f110d0a3e02.png)

this is where the problems start, because for my current kernel it doesn't compile in the least and the problem I don't understand where it can be.
Consulting the error log file gives me this, but I don't understand if it is a kernel problem or a Wireguard problem.

![immagine](https://user-images.githubusercontent.com/43168947/75235883-3fdb6600-57bd-11ea-9758-79e568efe6ba.png)

Also, if I try to see if it has loaded wireguard or to see if something is starting, I get nothing and the following error.

![immagine](https://user-images.githubusercontent.com/43168947/75236561-3ef70400-57be-11ea-90c0-60e9b80e361c.png)
And so if I try to start it, it gives me errors like

![immagine](https://user-images.githubusercontent.com/43168947/75236684-6cdc4880-57be-11ea-99e5-d5208fefbf2e.png)
with root mode


Thanks a lot in advance for the assistance!

**Comment by frank-w** [comment]
Problem with fixdep is maybe because it's not a armhf binary...remove it and maybe start compilation of kernel so that this binary is build directly on r2

have no idea why wireguard takes 4.19.x source instead of 5.4...
