### ISSUE TITLE
Enable squashfs support in 5.4-main

### ISSUE THREAD

**Issue by martinl** [frank-w/BPI-R2-4.14#76]
Hi,

first, I would like to thank you for maintaining the banana-pi r2 kernel and u-boot forks. It still took some work but setting things up were much easier than few years ago when I purchased BPI-R2.

Can you please enable squashfs in the 5.4-main branch, so lxc would work.

I added squashfs as module and recompiled to verify that lxc works. But I would prefer not to maintain another fork only for that.

with best regards,
Martin

**Comment by frank-w** [comment]
added with commit 95d702080506564add9fcd1a4a848314e62015c5 in 5.4-main (and in 5.8-main too)
