### ISSUE TITLE
modprobe: ERROR: could not insert 'ath9k' : Exec format error

### ISSUE THREAD

**Issue by hyunhi2** [frank-w/BPI-R2-4.14#78]
Hi, I'm trying to use wlan with atheros NIC on BPI-R2-V1.2.
First, I burned the bpi-r2-buster_5.4.58 image on SD card and it seemed to work well. I installed some packages including pciutils through ethernet and checked NIC well connected.
And then I have changed the configuration little bit to add ath9k module, executed ./build.sh to build kernel, and inserted directly on SD card.
Now, ath9k is installed, but Exec format error occurs when I try to modprobe the module.
mac80211 cannot be inserted because of the same error.

Any help would be appreciated.

**Comment by frank-w** [comment]
hi

afair ath9k should be already available in my image. for format-error, how do you compile/install kernel (crosscompile,...)? are you sure you booted your new kernel? you have to change uEnv.txt matching your new kernel-binary (uImage)

maybe you need to make clean/mrproper before

**Comment by hyunhi2** [comment]
bpi-r2-buster_5.4.58 image  from https://drive.google.com/drive/folders/1oP7jy1KrrIOifvImo2nQ59wx3_9hHkgk  was used.
mediatek was the only driver for wireless network.

I just followed the instructions. installed the crosscompile packages, changed the ath9k configuration, and execute ./build.sh with my xubuntu 16.04 kernel 4.15

initially there was no uEnv.txt, so I was stuck when installing the kernel on SD card. I just wrote an empty file named 'uEnv.txt'.  I assumed no change was required because kernel version is the same and I just changed configuration a little bit.

Should I set things like kaddr, rdaddr except for kernel name? Where can I get those values?

I'll try after changing uEnv.txt. Thanks for your help.

**Comment by frank-w** [comment]
You install a new binary. I'm not sure if i use uImage as name which will be used on installing by build.sh.

You use build.sh install after building it?

You can use "build.sh uenv" to open  uenv.txt.

Uenv.txt should be there on bpi_boot partition (1) in bananapi/bpi-r2/linux

If name is same, you should see a new build time if you run uname -a in debian. If it is old you did not boot your kernel.

Seems i have not yet enabled ath9k as i thought

https://github.com/frank-w/BPI-R2-4.14/blob/5.4-main/arch/arm/configs/mt7623n_evb_fwu_defconfig

**Comment by hyunhi2** [comment]
Should I build before using build.sh? I just use build.sh.
is 'make' command all i need to do for building it?

I just tried build.sh, but it just opened the 'uenv.txt'. No uenv.txt at bpi-r2-buster_5.4.58 image, so i tried uenv.txt on 4.14 after changing kernel name and a few commands below, but the boot failed.

I'm new to this, so need more detailed instructions. thank you.
```

#
## uEnv.txt
#
bpi=bananapi
board=bpi-r2
chip=mt7623n
service=linux
#
##
#
kernel=uImage
kernel=uImage_5.4.48-main

#kernel44=uImage_4.4.129
#kernel49=uImage_4.9.96
#kernel414=uImage_4.14.48-main
#kernel416=uImage_4.16.14-main
#kernel417=uImage_4.17.1-main
#

#newloadenv=mmc init; run loadbootenv; env import -t ${scriptaddr} ${filesize}
##
#
kaddr=0x84000000
rdaddr=0x86000000
#
##
#
root=/dev/mmcblk0p2 rootfstype=ext4 rootwait
console=earlyprintk console=tty1 fbcon=map:0 console=ttyS0,115200

#bootopts=vmalloc=496M debug=7 initcall_debug=0 video=1280x720-32 drm.debug=0x7
#bootopts=vmalloc=496M debug=7 initcall_debug=0 video=720x480@60 drm.debug=0x7
#bootopts=vmalloc=496M debug=7 initcall_debug=0 video=1024x768@60 drm.debug=0x7
bootopts=vmalloc=496M debug=7 initcall_debug=0 video=1920x1080 drm.debug=0x7 netcfg/do_not_use_netplan=true
#
##
#
abootargs=setenv bootargs board=${board} console=${console} root=${root} service=${service} ${bootopts}
#
##
#
ahello=echo Banana Pi ${board} chip: $chip Service: $service
#
##
#
aboot=if fatload $device $partition $rdaddr ${bpi}/berryboot.img; then bootm $kaddr $rdaddr ; else bootm $kaddr; fi
#
##
#
aload_kernel=fatload $device $partition $kaddr ${bpi}/${board}/${service}/${kernel}
#
##
#
uenvcmd=run ahello abootargs aload_kernel aboot

#new bootmenuentries (start at bootmenu_7) require reload bootmenu because uenv.txt is not loaded before display menu
boot54=run newloadenv; setenv kernel ${kernel}; printenv; run newboot
bootmenu_7=8. Boot kernel 5.4.=run boot54

#
## END
#

```

**Comment by frank-w** [comment]
No call of make as it requires crosscompile setup. Build.sh does all. As readme says...

```
./build.sh importconfig #import default config
./build.sh config #menuconfig to add ath9k
./build.sh #without param to build and ask for install
./build.sh uenv #to open uenv.txt on sdcard (if still mounted)
```
At the end of uenv.txt just add

kernel=your_uImage_name

**Comment by hyunhi2** [comment]
i thought i missed something. i used the first three commands, but it was not successful.
after just adding kernel name, i am able to find ath9k module now.
Thank you for your prompt and kind response.
