### ISSUE TITLE
SD-Card not found!

### ISSUE THREAD

**Issue by usermigallon** [frank-w/BPI-R2-4.14#87]
Hi, I have this "SD-Card not found!"

**Comment by frank-w** [comment]
can you please a bit more exactly? where did you get the error? on building/install or on running the kernel?

i guess while try to install via my build.sh

which operating system do you use? is BPI-BOOT/BPI-ROOT mounted to /media/$USER/? this is what the script checks

**Comment by usermigallon** [comment]
I use Ubuntu 20.04, media /dev/sde
./build.sh importconfig
./build.sh config
 ./build.sh
I choose 2
1) pack
2) install to SD-Card
3) deb-package
4) upload
choice [1234]:2
Install Kernel to SD Card
generate branch vars...
getting git branch: 
* 5.4-main
kernbranch:5.4-main,gitbranch:-main
uImage-filename: uImage_5.4.150-main /dev/sde 
Name: uImage_5.4.150-main /dev/sde
Press [enter] to copy data to SD-Card...
SD-Card not found!

**Comment by frank-w** [comment]
do you try to install to usb-stick/ssd/hdd?

build.sh uses /media/$USER/BPI-BOOT / BPI_ROOT to install, if your mountpoint differs to it you have to change occourances of this mountpoint with yours

**Comment by usermigallon** [comment]
I have not install usb-stick/ssd/hdd

**Comment by frank-w** [comment]
(where) is your sdcard mounted?

**Comment by usermigallon** [comment]
/media/user/7F3D-3FFE or /dev/sde

**Comment by frank-w** [comment]
OK, /media/user/7F3D-3FFE is your mountpoint, i guess because you miss the label in filesystem.

do you build for r2 or r64 (new bootchain)?

please show output of 

`mount | grep /dev/sde`
`fdisk -l /dev/sde`

**Comment by usermigallon** [comment]
mount | grep /dev/sde
/dev/sde1 on /media/resu/7F3D-3FFE type vfat (rw,nosuid,nodev,relatime,uid=1000,gid=1000,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,showexec,utf8,flush,errors=remount-ro,uhelper=udisks2)

sudo fdisk -l /dev/sde
Disk /dev/sde: 29,74 GiB, 31914983424 bytes, 62333952 sectors
Disk model: MassStorageClass
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xf389ccae

Device     Boot Start      End  Sectors  Size Id Type
/dev/sde1        2048 62332927 62330880 29,7G  c W95 FAT32 (LBA)

**Comment by frank-w** [comment]
you have no valid BPI image on your sdcard...it looks like a blanko sdcard.

you need a running system before installing new kernel

e.g. my debian buster/bullseye image you can found on bpi-forum

**Comment by usermigallon** [comment]
I build r2

**Comment by usermigallon** [comment]
my sd card is empty

**Comment by usermigallon** [comment]
Need I to install first a Debian firstly install on my sd card?

**Comment by frank-w** [comment]
you can use another image too, but you need bootable image first...this repo is only linux-kernel which is loaded by bootchain (preloader,bootheaders,uboot) so this needs to be installed first

**Comment by usermigallon** [comment]
ok, thank you very much for your help, I will install first Debian os

**Comment by usermigallon** [comment]
I need Debian or Ubuntu?

**Comment by frank-w** [comment]
you need a compatible system with the right partitions to make install work

my kernel / build-script is only prepared for this.

e.g. openwrt uses another way to load kernel and there it cannot be replaced that easy (rebuild openwrt needed).

which system do you want to use?

**Comment by usermigallon** [comment]
ok openwrt , I try to install , Debian, Ubuntu, openwrt and lede, but all are incomplete

**Comment by usermigallon** [comment]
I install openwrt in sd card, and I have same SD-Card not found!

**Comment by frank-w** [comment]
Openwrt is not compatible as i've wrote above and it will miss my changes (e.g. internal wifi for r2, some patches for r64 like bluetooth/pcie),

debian is the most actual OS as i have not make a newer ubuntu image. If you want ubuntu you can replace rootfs from debian-image with bootstrapped ubuntu, change rootpw and make some small changes like i wrote down in my wiki

**Comment by usermigallon** [comment]
So I install Debian?

**Comment by frank-w** [comment]
yes

**Comment by usermigallon** [comment]
I have the same with Debian SD-Card not found!

**Comment by frank-w** [comment]
which debian have you used? do you see the mountpoint /media/$USER/BPI-BOOT/BPI-ROOT?

**Comment by usermigallon** [comment]
I use Debian 11 and that  is my command
./build.sh
Build Kernel
Cleanup Kernel Build
needed: make u-boot-tools bc gcc libc6-dev libncurses5-dev ccache libssl-dev
generate branch vars...
getting git branch: 
* 5.4-main
kernbranch:5.4-main,gitbranch:-main
  DTC     arch/arm/boot/dts/mt2701-evb.dtb
  DTC     arch/arm/boot/dts/mt6580-evbp1.dtb
  DTC     arch/arm/boot/dts/mt6589-aquaris5.dtb
  DTC     arch/arm/boot/dts/mt6592-evb.dtb
  DTC     arch/arm/boot/dts/mt7623a-rfb-emmc.dtb
  DTC     arch/arm/boot/dts/mt7623a-rfb-nand.dtb
  DTC     arch/arm/boot/dts/mt7623n-rfb-emmc.dtb
  DTC     arch/arm/boot/dts/mt7623n-bananapi-bpi-r2.dtb
  DTC     arch/arm/boot/dts/mt7629-rfb.dtb
  DTC     arch/arm/boot/dts/mt8127-moose.dtb
  DTC     arch/arm/boot/dts/mt8135-evbp1.dtb
  CALL    scripts/atomic/check-atomics.sh
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  Kernel: arch/arm/boot/Image is ready
  Building modules, stage 2.
  MODPOST 220 modules
  OBJCOPY arch/arm/boot/zImage
  Kernel: arch/arm/boot/zImage is ready
Image Name:   Linux Kernel 5.4.150-main
Created:      Wed Dec 22 11:57:55 2021
Image Type:   ARM Linux Kernel Image (uncompressed)
Data Size:    8581016 Bytes = 8379.90 KiB = 8.18 MiB
Load Address: 80008000
Entry Point:  80008000
build uImage without appended DTB...
Image Name:   Linux Kernel 5.4.150-main
Created:      Wed Dec 22 11:58:07 2021
Image Type:   ARM Linux Kernel Image (uncompressed)
Data Size:    8546152 Bytes = 8345.85 KiB = 8.15 MiB
Load Address: 80008000
Entry Point:  80008000
===========================================
1) pack
2) install to SD-Card
3) deb-package
4) upload
choice [1234]:2
Install Kernel to SD Card
generate branch vars...
getting git branch: 
* 5.4-main
kernbranch:5.4-main,gitbranch:-main
uImage-filename: uImage_5.4.150-main
Name: uImage_5.4.150-main
Press [enter] to copy data to SD-Card...
SD-Card not found!

**Comment by usermigallon** [comment]
if I use this ./build.sh /media/user/a5dcd082-db07-4b55-a1bc-4193f3680cdf/ do not work too 

./build.sh /media/user/a5dcd082-db07-4b55-a1bc-4193f3680cdf/
unknown command /media/user/a5dcd082-db07-4b55-a1bc-4193f3680cdf/

**Comment by frank-w** [comment]
you cannot pass mountpoint to build.sh, only predefined commands (shown with ./build.sh help)

the mountpoint looks like it is not a fat-partition. as i've said, the script looks for /media/$USER/BPI-BOOT

https://github.com/frank-w/BPI-R2-4.14/blob/5.4-main/build.sh#L316

so make sure your boot-partition has this label (my images do this), but i'm not use other images have this

so just show your partition table

this is my last Image for R2...(i guess you have this device):
https://forum.banana-pi.org/t/bpi-r2-debian-bullseye-image/12592

**Comment by usermigallon** [comment]
This is my sd
[](url)https://ibb.co/0cJBbWr

**Comment by usermigallon** [comment]
Maybe have you got a Debian to suggest ?

**Comment by usermigallon** [comment]
I bought this card because there were 4 rj45 ports, but I regret, this card it is good for the trash

**Comment by frank-w** [comment]
your image still show no image flashed to card...you have to use dd or similar tool to write image to card...not copy file to the partition. image have to be uncompressed first

`gunzip imagefile.gz`
`dd if=imagefile of=/dev/sdX bs=10M status=progress`

i posted link to my last debian image here: 
https://github.com/frank-w/BPI-R2-4.14/issues/87#issuecomment-999491218

i know first steps are hard, but it is different to install OS on x86...this is not a hardware-problem :)
i do the most for this board (i did this all in my free time and i'm no employee of bpi/mtk) and have it running for over 4 years now as main-router

**Comment by usermigallon** [comment]
I use wrt3200acm, and I'm glad, I bought banana pi-r2 to be able to hack, but there is not a lot of documentation and it is not very clear.
Now I have this out put 
uImage:
/media/resu/BPI-BOOT/bananapi/bpi-r2/linux/uImage_5.4.150-main

by default this kernel-/dtb-file will be loaded (kernel-var in uEnv.txt):
it must take a while ?

**Comment by usermigallon** [comment]
it's normal that it always stays in ?
by default this kernel-/dtb-file will be loaded (kernel-var in uEnv.txt):

**Comment by frank-w** [comment]
no, maybe a bug....do you have a uEnv.txt in the linux-folder? if not create one and add

`kernel=uImage_5.4.150-main`

**Comment by usermigallon** [comment]
No, I don't have uEnv.txt 
It ask me this at start up
install kernel with DT [yn]? y 
install kernel with separate DT [yn]? n
It's right?

**Comment by usermigallon** [comment]
The image I have download  [https://drive.google.com/file/d/1VbV_IaUy92p1bIrd74sahs77LQNSQEVd/view?usp=sharing](url) do not work.

**Comment by frank-w** [comment]
then i missed creating an empty uEnv.txt in the image (it's not needed if there is no change compared to uboot builtin environment). but build.sh should create one if none exists.

yes for r2 default is kernel with builtin devicetree...else it needs to loaded separately that is a bit more complex....this is for experimenting with dt overlays.

**Comment by usermigallon** [comment]
I try your image [https://drive.google.com/file/d/1VbV_IaUy92p1bIrd74sahs77LQNSQEVd/view?usp=sharing](url) 
without modifying any thing and do not work.

**Comment by frank-w** [comment]
you have it unpacked (gunzip) and written img-file to sdcard (not to partition) with dd??

you have uart-cable connected?

what do you mean with "does not work", which output on serial console?

**Comment by usermigallon** [comment]
1°) I use sd card connected to laptop, I have uart-cable but I do not use
 [https://www.aliexpress.com/item/33000531104.html?spm=a2g0o.productlist.0.0.74f230adrMGnv6&algo_pvid=0705413a-ffbe-4cc2-90c0-bced790dc3b6&algo_exp_id=0705413a-ffbe-4cc2-90c0-bced790dc3b6-9&pdp_ext_f=%7B%22sku_id%22%3A%2266952889056%22%7D](url) 
2°) I done `sudo dd if=bpi-r2-buster_5.4.58.img of=/dev/sde bs=4M status=progress`
3°) Do not work scan my network with angry scan Ubuntu, lights of my rj45 connection of my  bpi-r2 are  blinking but not any ip adress.

**Comment by frank-w** [comment]
with an uart cable you are able to see anything if something not work ;)

i'm not sure which network-config i used in buster image...you can look/change in BPI-ROOT/etc/network/interfaces

blinking means it is running and network-drivers are loaded for ethernet of SoC and switch :)

**Comment by usermigallon** [comment]
1°) I use sd card connected to laptop, I have uart-cable but I do not use
 [https://www.aliexpress.com/item/33000531104.html?spm=a2g0o.productlist.0.0.74f230adrMGnv6&algo_pvid=0705413a-ffbe-4cc2-90c0-bced790dc3b6&algo_exp_id=0705413a-ffbe-4cc2-90c0-bced790dc3b6-9&pdp_ext_f=%7B%22sku_id%22%3A%2266952889056%22%7D](url) 
2°) I done `sudo dd if=bpi-r2-buster_5.4.58.img of=/dev/sde bs=4M status=progress`
3°) Do not work scan my network with angry scan Ubuntu, lights of my rj45 connection of my  bpi-r2 are  blinking but not any ip adress.

**Comment by frank-w** [comment]
have you got it working? wrong subnet of ethernet?

**Comment by usermigallon** [comment]
I don't know  to use uart cable, can you give me tuto link?

**Comment by usermigallon** [comment]
No, it doesn't work

**Comment by frank-w** [comment]
https://www.fw-web.de/dokuwiki/doku.php?id=en:bpi-r2:debug-uart

**Comment by usermigallon** [comment]
I will test tomorrow, and I will tell you what happen, thank you for your patient

**Comment by usermigallon** [comment]
Hello, I just did what is in your tutorial and it works, it was an ip problem, but still have the same problem building, Have you got and idea ? [https://pastebin.com/xb6CBR7N](url)

**Comment by frank-w** [comment]
build looks successful...you mean the hang on display current kernel loaded? need to figure out why the hang occours basicly it is only a grep that should not hang

**Comment by usermigallon** [comment]
it stops with the build and it puts
`uImage:
/media/user/BPI-BOOT/bananapi/bpi-r2/linux/uImage_5.4.150-main

by default this kernel-/dtb-file will be loaded (kernel-var in uEnv.txt):`
[https://postimg.cc/Z0Htr4fv](url)

**Comment by frank-w** [comment]
it's no more build...it's after install, you can try to add an (empty) uEnv.txt in /media/user/BPI-BOOT/bananapi/bpi-r2/linux/

add line to this file:

kernel=uImage_5.4.150-main

**Comment by usermigallon** [comment]
Works, thank you so much Franck

**Comment by frank-w** [comment]
could you try if this build.sh fixes the problem?

https://github.com/frank-w/BPI-R2-4.14/blob/5.16-rc/build.sh

just rename the uEnv.txt you've created

**Comment by usermigallon** [comment]
Here you have the logs, its works
https://pastebin.com/6FSTLSk9
