### ISSUE TITLE
Debian package > 5.4 have no kernel with dtb

### ISSUE THREAD

**Issue by Josue-T** [frank-w/BPI-R2-4.14#88]
Hello,

While I was tring to upgrade my kernel from 5.4 to 5.10 I detected that in the debian package there are no kernel image with dtb. So in `/boot/bananapi/bpi-r2/linux/` I only have this file `uImage_nodt-5.10.90-bpi-r2-main` and the `dtb` directory.

So is it normal that we don't have the image with dtb ? And if yes how can I start with this image from uboot ?

**Comment by frank-w** [comment]
do you use the deb from the choice after build or the pack_debs?

the deb-packing after choice should work

https://github.com/frank-w/BPI-R2-4.14/blob/5.10-main/build.sh#L535

the other is defined in the kbuild system and a bit more complex

https://github.com/frank-w/BPI-R2-4.14/blob/5.10-main/scripts/package/builddeb#L143

here the uImage with dtb is missing...the standalone dtb should be there

```
--- a/scripts/package/builddeb
+++ b/scripts/package/builddeb
@@ -146,6 +146,8 @@ bpi-r64|bpi-r2)
        if [ "$board" = "bpi-r64" ];
        then
                cp ./$board.itb "$tmpdir/boot/bananapi/$board/linux/$board-$version.itb"
+       else
+               cp ./uImage "$tmpdir/boot/bananapi/$board/linux/uImage_$version"
        fi
        source_image_path="./uImage_nodt"
        ;;
```
make sure in build.sh - function build{} the dtb is copied to $board.dtb, maybe use the build.sh from 5.17-rc tree

as far as i see current code includes the dtb's (also for other boards) in /usr/lib/linux-image-5.17.0-rc1-bpi-r2/

`dpkg -c ../linux-image-5.17.0-rc1-bpi-r2_5.17.0-rc1-bpi-r2-1_armhf.deb | grep 'uImage\|dtb'`

**Comment by Josue-T** [comment]
Hello,

Thanks for your answer. Well I don't really know how you build the package, the package which has the issue is the package that I got here: https://github.com/frank-w/BPI-R2-4.14/releases/tag/CI-BUILD-5.10-main-5.10.90-2022-01-13_0818

Igot this file: linux-image-5.10.90-bpi-r2-main_5.10.90-bpi-r2-main-1_armhf.deb

**Comment by frank-w** [comment]
Ok,you do not build yourself and use deb from releases...this is built with pack_debs.

I will upload fix tomorrow

**Comment by Josue-T** [comment]
Thanks for the fix, and thanks a lot for all your work to maintain this kernel.

**Comment by frank-w** [comment]
last release contains these for boot partition
```
drwxr-xr-x root/root         0 2022-02-02 07:39 ./boot/bananapi/bpi-r2/linux/dtb/
-rw-r--r-- root/root     44389 2022-02-02 07:39 ./boot/bananapi/bpi-r2/linux/dtb/bpi-r2-5.10.90-bpi-r2-main.dtb
-rw-r--r-- root/root   8245660 2022-02-02 07:39 ./boot/bananapi/bpi-r2/linux/uImage_5.10.90-bpi-r2-main
-rw-r--r-- root/root   8210888 2022-02-02 07:39 ./boot/bananapi/bpi-r2/linux/uImage_nodt-5.10.90-bpi-r2-main
```

i wonder why your dtb directory was empty...

thx for report :)
