### ISSUE TITLE
[Question] 5.15 & hwnat

### ISSUE THREAD

**Issue by alxchk** [frank-w/BPI-R2-4.14#92]
I have a question regarding branch 5.15. According to the table, HW NAT should be supported. However I couldn't find implementation in these sources. Where is it?

**Comment by frank-w** [comment]
Mainline hwnat is called flow offload it is part of nftables framework. You can look into 5.10-hnat where i have backported neccessary Patches to see the code (top commits - first page)

**Comment by alxchk** [comment]
Found, thanks

**Comment by frank-w** [comment]
Here i have an example configuration

https://wiki.fw-web.de/doku.php?id=en:bpi-r2:network:nftables#hwnat
