### ISSUE TITLE
cryptodev not available on kernel 6.1

### ISSUE THREAD

**Issue by Josue-T** [frank-w/BPI-R2-4.14#96]
Hello,

I discovered that cryptodev module was not enabled on kernel 6.1. Is it normal ? And is it possible to enable it ?

Thanks

**Comment by frank-w** [comment]
Cryptodev needs additional work and 6.1 is really fresh (wanted to get kernel itself working for all devices first) :) just have not found time to add it (needs external code added).

Do you need it for r2 or other device?

As a note: 6.1 for r2 does not support internal wifi

**Comment by frank-w** [comment]
can you please test branch 6.1-cryptodev?

at least for r2 compile works using

```
./build.sh importconfig
./build.sh
./build.sh cryptodev
```

r64 seems also working (compile) using aarch64 crosscompiler...

**Comment by Josue-T** [comment]
Hello,

Thanks for the answer. Yes it's for R2 (only).

Thanks it might be a bit complicated for me to test this, but I will try when I will have some time.

**Comment by frank-w** [comment]
Why is it complicated? It is similar to older kernels...clone repo,change branch to 6.1-cryptodev and then build kernel and cryptodev module,install to your r2 and test it. I have no experience with cryptodev itself,only added code and make it compile

**Comment by Josue-T** [comment]
oh sorry, it's just because I'm too busy these time, but yes it's not complicated, it juste take some time.

**Comment by frank-w** [comment]
Have done tests with it?

**Comment by frank-w** [comment]
No response
