### ISSUE TITLE
is it possible to resize the filesystem when using SD card?

### ISSUE THREAD

**Issue by gustavobsch** [frank-w/BPI-R2-4.14#98]
I'm trying to make use of all available space however when running parted it says the SD card is 8GB and there's no additional space to allocate. 

Do I need to re-create the partition table?

**Comment by frank-w** [comment]
You have used the img file from my uboot-repo?

You can imho resize BPI-ROOT Partition with gparted or create an additional partition for data...7/8 gb should be enough for rootfs.

**Comment by gustavobsch** [comment]
Thanks, I was able to resize it using parted
