### ISSUE TITLE
SFP1 vlan not working on the r3

### ISSUE THREAD

**Issue by gustavobsch** [frank-w/BPI-R2-4.14#99]
Hi, is there any workaround for the vlan not working on SFP1?

Thanks!

**Comment by frank-w** [comment]
There are patches for 6.2, see 6.2-rc branch. Have not got it working by backporting to 6.1. there is still an issue with vlan on dsa port when using a vlan-aware bridge on other ports

**Comment by gustavobsch** [comment]
I tested and it works but is not stable.. I'm not sure what I'm doing maybe rebooting the device will make it stop working

**Comment by gustavobsch** [comment]
Thank you Frank, it's working now!
